---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
      - id: trailing-whitespace


  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
      - id: poetry-install
      - id: poetry-lock
      - id: poetry-export


  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black


  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort


  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          [
            "-rn",  # Only display messages
            "-sn",  # Don't display the score
          ]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
