---
version: '3'
services:

  # We are setting up redis with appendfsync set to always here. This ensures
  # maximum data durability at the cost of performance.
  # If you require high performance you might consider setting this to everysec
  # instead which syncs to disk every second.
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --appendfsync always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

#   Uncomment this if you want to run Worker / Coordinator nodes
#   worker:
#     image: ghcr.io/ls1intum/storage-benchmarking
#     command: worker -d /tmp -g GROUP
#     volumes:
#       - "worker_data:/tmp"
#     environment:
#       REDIS_HOST: redis
#       REDIS_PORT: 6379

#   coordinator:
#     image: ghcr.io/ls1intum/storage-benchmarking
#     command: coordinator -g GROUP1 GROUP2 -f /app/job_files/blocks.ini
#     environment:
#       REDIS_HOST: redis
#       REDIS_PORT: 6379

volumes:
  redis_data:
    driver: local
#   worker_data:
#     driver: local
