---
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: fio
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fio
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
