---
version: '3'
services:

  # We are setting up redis with appendfsync set to always here. This ensures
  # maximum data durability at the cost of performance.
  # If you require high performance you might consider setting this to everysec
  # instead which syncs to disk every second.
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --appendfsync always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  redis_data:
    driver: local
