---
name: Build and Push Docker image

"on":
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push docker image
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ghcr.io/ls1intum/storage-benchmarking
      docker-file: ./Dockerfile
